# 数据预处理

In [8]:
from sklearn.preprocessing import StandardScaler,Normalizer,MinMaxScaler,OneHotEncoder
import numpy as np

In [10]:
###标准化，是特征值 服从正态分布，高斯分布
data =[[0,1],[1,2],[2,3]]
scaler = StandardScaler()
scaler.fit(data)   ##求得期望和方差
print(scaler.transform(data)) ##使用期望和方差对数据进行处理

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [17]:
##Normalization 使用范数，将入参正则化到 [0,1] 之间
X = [[ 1., -1.,  2.], [2.,  0.,  0.], [ 0.,  1., -1.]]
normalizer = Normalizer().fit(X)
print(normalizer)
normalizer.fit_transform(X)

Normalizer(copy=True, norm='l2')


array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [22]:
##MinMaxScaler 将特征值数据压缩在0 到1 之间
yData = [[ 1., -1.,  2.],[ 2.,  0.,  0.], [ 0.,  1., -1.]]
maxMinScaler = MinMaxScaler()
maxMinScaler.fit(yData)
print(maxMinScaler.fit_transform(yData))
print(maxMinScaler.data_max_)
print(maxMinScaler.data_min_)

[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
[2. 1. 2.]
[ 0. -1. -1.]


# 文档型转换成向量

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [2]:
 corpus = [
...     'This is the first document.',
...     'This is the second second document.',
...     'And the third one.',
...     'Is this the first document?',
... ]

In [5]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

In [7]:
X.toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

# 离散数据转换成向量（独热编码-OneHotEncode ：1 of k(哑变量)）

In [9]:
#sex:{male, female, other}

enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])
enc.transform([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]).toarray()

array([[1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0.]])

解释独热编码原理：每一列代表一个类别, 第一列 为 0 1 0 1， 分类为 0 1，第二列分类为： 0 1 2； 第三列分类为： 0 1 2 3
所以对[0,0,3] 编码 为 1 0 1 0 0 0 0 0 1（第一列 0 出现为 1 0 ， 1 出现为0 1）

# 多项式 PolynomialFeatures()

模型评价：
分类模型：
 ROC曲线
 AUC 值
 混淆矩阵
 准确率
 召回率
    