np.linalg.norm(求范数)

x_norm=np.linalg.norm(x, ord=None, axis=None, keepdims=False) 

![image.png](attachment:image.png)

③axis：处理类型

axis=1表示按行向量处理，求多个行向量的范数

axis=0表示按列向量处理，求多个列向量的范数

axis=None表示矩阵范数。

④keepding：是否保持矩阵的二维特性

True表示保持矩阵的二维特性，False相反

In [18]:
import numpy as np  
x = np.array([  
    [0, 3, 4],  
    [1, 6, 4]])  
#默认参数ord=None，axis=None，keepdims=False  
print ("默认参数(矩阵2范数，不保留矩阵二维特性)：",np.linalg.norm(x))
print("矩阵2范数，保留矩阵二维特性：",np.linalg.norm(x,keepdims=True))  
  
print("矩阵每个行向量求向量的2范数：",np.linalg.norm(x,axis=1,keepdims=True)) 
print("矩阵每个列向量求向量的2范数：",np.linalg.norm(x,axis=0,keepdims=True)) 
  
print("矩阵1范数：",np.linalg.norm(x,ord=1,keepdims=True)) 
print("矩阵2范数：",np.linalg.norm(x,ord=2,keepdims=True))  
print("矩阵∞范数：",np.linalg.norm(x,ord=np.inf,keepdims=True))  
  
print("矩阵每个行向量求向量的1范数：",np.linalg.norm(x,ord=1,axis=1,keepdims=True))

默认参数(矩阵2范数，不保留矩阵二维特性)： 8.831760866327848
矩阵2范数，保留矩阵二维特性： [[8.83176087]]
矩阵每个行向量求向量的2范数： [[5.        ]
 [7.28010989]]
矩阵每个列向量求向量的2范数： [[1.         6.70820393 5.65685425]]
矩阵1范数： [[9.]]
矩阵2范数： [[8.70457079]]
矩阵∞范数： [[11.]]
矩阵每个行向量求向量的1范数： [[ 7.]
 [11.]]


In [ ]:
#####numpy 数组 行列比较

In [27]:
x1 = np.array([0, 3, 4])    ###秩为3的数组
print(x1.shape)
print(x1)

(3,)
[0 3 4]


In [28]:
x2 = np.array([[0, 3, 4]])     ###矩阵
print(x2.shape)
print(x2)

(1, 3)
[[0 3 4]]


In [21]:
x3 = np.array([[0, 3, 4],[1, 6, 4]])
print(x3.shape)

(2, 3)


In [26]:
x4 = np.array([[[0, 3, 4],[1, 6, 4]]])
print(x4.shape)
print(x4.reshape(x4.shape[0],-1))

(1, 2, 3)
[[0 3 4 1 6 4]]


In [29]:
### 初始化数组
w = np.zeros((4, 1))
print(w)

[[0.]
 [0.]
 [0.]
 [0.]]


In [40]:
x4 = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print(x4.shape)
print(x4.reshape(x4.shape[0],-1))
print(np.squeeze(x4).shape)

(3, 3, 2)
[[0.67826139 0.29380381 0.90714982 0.52835647 0.4215251  0.45017551]
 [0.92814219 0.96677647 0.85304703 0.52351845 0.19981397 0.27417313]
 [0.60659855 0.00533165 0.10820313 0.49978937 0.34144279 0.94630077]]
(3, 3, 2)


In [36]:
###测试np.squeeze 的功能, ### 从数组的形状中删除单维条目，即把shape中为1的维度去掉
x5 = np.array([[[0], [1], [2]]])
print(x5.shape)

(1, 3, 1)


In [39]:
X6 = np.squeeze(x5)
print(X6.shape)

(3,)


In [ ]:

print(x)
"""
x=

[[[0]
  [1]
  [2]]]
"""
print(x.shape)  # (1, 3, 1)

x1 = np.squeeze(x)  # 从数组的形状中删除单维条目，即把shape中为1的维度去掉


print(x1)  # [0 1 2]
print(x1.shape)  # (3,)